<?php

namespace Games\SnakeBundle\Entity;

/**
 * SnakeStartLocationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnakeStartLocationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllFetchArray() {
        $qb = $this->getEntityManager()
                    ->createQueryBuilder();
        $qb->select("p")
           ->from("GamesSnakeBundle:SnakeStartLocations", "p");
        return $qb->getQuery()->getArrayResult();
    }
}
